name: Patch when updating dependencies

on:
  pull_request:
    types: [closed] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        env:
          PR: ${{ toJson(github.event.pull_request) }}
        run: echo "$PR"
        
      - name: Test
        if: github.event.pull_request.labels[0].name == 'dependencies'
        run: echo 'ok'
        
      - name: Checkout repository
        if: github.event.pull_request.labels[0].name == 'dependencies' && github.event.pull_request.merged == true
        uses: actions/checkout@v1.0.0
        
      - name: Patch version
        if: github.event.pull_request.labels[0].name == 'dependencies' && github.event.pull_request.merged == true
        run: npm version patch

      - name: Set up Node.js for NPM
        if: github.event.pull_request.labels[0].name == 'dependencies' && github.event.pull_request.merged == true
        uses: actions/setup-node@v1.2.0
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '10.x'

      - name: Install dependencies
        if: github.event.pull_request.labels[0].name == 'dependencies' && github.event.pull_request.merged == true
        run: npm ci

      - name: Publish package to NPM
        if: github.event.pull_request.labels[0].name == 'dependencies' && github.event.pull_request.merged == true
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Git push
        if: github.event.pull_request.labels[0].name == 'dependencies' && github.event.pull_request.merged == true
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
